Catcher streamline
HERA-Team/paper_gpu pull request #79
Opened 2022-09-24 03:39 UTC by AaronParsons

Couple more changes to control restructuring, and a vital change to CATCHER BUFFER size that gets rid of packet loss.

2022-09-24 21:22 UTC, plaplant requested changes
Thanks @AaronParsons! Glad to hear that this solves the traffic bottleneck on site. What was the specific change that fixed things? It looks like some of the packet/block math changed, but I'm curious what was most important.

Most of my comments are about removing commented out code rather can keeping it around. Though I appreciate all of the explanatory comments, they are very helpful.

2022-09-25 21:51 UTC, AaronParsons commented on control_software/scripts/hera_catcher_up.py
> +
This was a partial roll out of better handshaking to get away from magical sleeps, but it doesn't work yet. Let's keep it for now to see if I can get this working later.

2022-09-25 21:51 UTC, AaronParsons commented on control_software/scripts/hera_catcher_up.py
> +#        continue
Same answer as above.

2022-09-25 21:52 UTC, AaronParsons commented on control_software/scripts/hera_catcher_up.py
>  run_on_hosts([args.host], python_source_cmd + ['cd', '/data;', 'hera_catcher_init.sh'] + init_args + ['0'], wait=True)
Er... aren't we?

2022-09-25 21:54 UTC, AaronParsons commented on src/hera_catcher_net_thread.c
> +  //int i;
It's attached to a block of error prints that I commented out but would like to fix so they actually work. When that happens, we can uncomment here.

2022-09-25 21:55 UTC, AaronParsons commented on src/hera_catcher_net_thread.c
> +  printf("net_thread: marking block_i=%d filled\n", block_i);
It does, and I'll take it out later, but for now, I need visibility into the microscopic stuff if things break...

2022-09-25 21:55 UTC, AaronParsons commented on src/hera_catcher_net_thread.c
> +    //}
I agree (as per above), but I'm not ready to sink any more time in this right now. Can we kick this down the road?

2022-09-25 21:56 UTC, AaronParsons commented on control_software/scripts/hera_catcher_up.py
>  run_on_hosts([args.host], python_source_cmd + ['cd', '/data;', 'hera_catcher_init.sh'] + init_args + ['0'], wait=True)
It looks to me like run_on_hosts is imported from that module.

2022-09-25 21:58 UTC, AaronParsons commented
I hear what you're saying on these comments wrt cleanup, but it mostly reflects work half-done that I'd like to lock in before proceeding further. Since last reveiw, I did add 1 more commit to fix the BDANANT bug that i think is freezing the autocorr thread.

2022-09-28 06:27 UTC, plaplant approved these changes

2022-09-28 06:28 UTC, merged